### ISSUE TITLE
Raw Input Issue with JSOn Decoder

### ISSUE THREAD

**Issue by RepairKit25** [guilhemmarchand/TA-jira-service-desk-simple-addon#142]
Hi Guilhem Marchand, 

This is excellent app add-on for Splunk and JIRA but the only issue I came across was this bug: 
 
 Problem at this line -> JSONDecodeError at "/opt/splunk/lib/python3.7/json/decoder.py", line 355 : Expecting value: line 1 column 1 (char 0);

I think the problem is that it either not recognized my credentials and data in JSON format or that there's something in the script that doesn't recognize anything like a raw value; I added a link below for an issue that might be the fix but I don't know; Please let me know if you need anything.

May I also recommend added all the JIRA Headers; like the Experimental API Header into the Build-in API Rest Call

Thanks,
RK25

**Comment by guilhemmarchand** [comment]
Hi @RepairKit25 

Thank you very much.

`Problem at this line -> JSONDecodeError at "/opt/splunk/lib/python3.7/json/decoder.py", line 355 : Expecting value: line 1 column 1 (char 0);

I think the problem is that it either not recognized my credentials and data in JSON format or that there's something in the script that doesn't recognize anything like a raw value; I added a link below for an issue that might be the fix but I don't know; Please let me know if you need anything.`

Are you able to retrieve JIRA info and/or create issues? Sorry it's not really clear at this point.

A new release (2.0.10) was published to address various aspects of the robustness of the JSON parsing, this could lead into this.

`May I also recommend added all the JIRA Headers; like the Experimental API Header into the Build-in API Rest Call
`

Thank you, I will start looking at this ASAP
