### ISSUE TITLE
Connect JIRA Splunk GCP 

### ISSUE THREAD

**Issue by Aiv4n7** [guilhemmarchand/TA-jira-service-desk-simple-addon#143]
Hi [guilhemmarchand.

We are trying to connect our instace of splunk in GCP with JIRA, but we have the next issue: 

ConnectionError at "/opt/splunk/lib/python3.7/site-packages/requests/adapters.py", line 516 : HTTPSConnectionPool(host='200.XX.XX.XXX', port=9090): Max retries exceeded with url: /rest/api/2/project (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 110] Connection timed out'))
 
Can ypu help us, if you know about a similar topic! 

Thanks, regards

**Comment by guilhemmarchand** [comment]
Hi @Aiv4n7

The Python exception is pretty clear, from the network perspective the connection cannot be established.

Either the outgoing traffic is restricted, either the target doesn't let you in.
If you have backend access you can simple use a curl and you will the same, if you are on Splunk Cloud because the port is not a standard port you need to request a firewall rule or use ACS to allow the outgoing traffic.

Guilhem

**Comment by guilhemmarchand** [comment]
I assume you could fix your issue @Aiv4n7
