### ISSUE TITLE
Fix - Splunk Cloud vetting - Force SSL Verification or the use of a CA bundle to validate the SSL verification

### ISSUE THREAD

**Issue by guilhemmarchand** [guilhemmarchand/TA-jira-service-desk-simple-addon#184]
**Fix - Splunk Cloud vetting - Force SSL Verification or the use of a CA bundle to validate the SSL verification**

**Comment by jess42** [comment]
@guilhemmarchand I haven't used your app before this was implemented, but the documentation refers to a check box in the event of trying to verify against a server which uses a valid 3rd part cert. I'm not seeing a checkbox, and am getting an error:

ConnectionResetError(104, 'Connection reset by peer')

We've validated everything else is exactly the same between this (done on Splunk Cloud) and the app installed on the HF (internal, as is our JIRA instance), so the only thing we can think of is the certs. Has anyone else seen this since the change was implemented? Thanks!
