### ISSUE TITLE
Search Head Cluster - Configuration Issue

### ISSUE THREAD

**Issue by Evotiona** [guilhemmarchand/TA-jira-service-desk-simple-addon#67]
Having issues in Splunk 7.3.3 with 3 clustered search heads getting app to work. Configuration works well in deployment server and staging server, no issues taking passwords.conf and settings.conf, but when deploying to cluster, configuration page no longer loads (just spins on the Add-On settings tab and Proxy tag) and REST API no longer works.

**Comment by guilhemmarchand** [comment]
Hi @Evotiona 

I believe your issue is due to Python3 requirements.

For Splunk Cloud certification purposes, it is required that the TA explicitly requires Python3, in the following files:

TA-jira-service-desk-simple-addon/default/alert_actions.conf

```
<code>
python.version = python3
```

And especially:

TA-jira-service-desk-simple-addon/default/restmap.conf

```
<code>
python.version = python3
```

Do the following, on your SHC deployer, create a copy of the following files, comment the python, and apply the SHC bundle:

```
cd /opt/splunk/etc/shcluster/apps/TA-jira-service-desk-simple-addon
mkdir local
cp -p default/commands.conf local/
cp -p default/restmap.conf local/
cp -p default/alert_actions.conf local/
```

Then make sure to add a # for each python line:

```
#python.version = python3
```

Push the bundle, once the bundle is applied and members restarted, this will work.

Let me know

**Comment by Evotiona** [comment]
Thanks for the quick reply! Working with system admins to perform this change now. 

Will this allow us to hit the configuration page in the GUI or will we need to ensure the user/password is saved correctly on deployment server and then pushed accordingly?

**Comment by guilhemmarchand** [comment]
Yes this should fix the issue of the setup page freezing @Evotiona  so not need to do the stuff on the SHC deployer

**Comment by guilhemmarchand** [comment]
@Evotiona 
Assuming your issue was fixed by forcing Python 2, I am closing this issue.
Please re-open and respond otherwise.
